@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources Manager" as Employee
participant "System" as System

activate Employee

    System <- Employee : Initiates a team proposal generation
    activate System

    Employee <-- System :Requests to choose a skill
    deactivate System

    System <- Employee : Selects a skill
    activate System

    Employee <-- System :Requests data (min & max collaborator size)
    deactivate System

    Employee -> System : Types team requirements
    activate System

    System -> Employee : Generate and displays team proposal
    deactivate System

    Employee -> System : Confirms or refuse team proposal
    activate System

    System --> Employee : Display operation successful
    deactivate System
@enduml