@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods
package "VFM System" {

title Domain Model - US008

class VehicleForCheckUp {
    Vehicle
}

class VFM {
}

class Vehicle {
         plateID
         brand
         model
         type
         tare
         grossWeight
         millage
         registerDate
         acquisitionDate
         maintenanceFrequency
         lastCheckUp
}

class MusgoSublime {
vatNumber
website
phoneNumber
email
}



MusgoSublime "1" - "*" Vehicle: has >
Vehicle "*"- "*" VehicleForCheckUp: contains >
VehicleForCheckUp "*" -- "1" VFM : informs >





@enduml