@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods
package "FM System" {

title User Story 008

class VehiclesForCheckUp {
number plate
brand
model
type
tare
gross weight
current Km
register date
Acquisition Date
Maintenance/Checkup Frequency (in Kms)


}

class FM {
}

class Vehicle {
number plate
brand
model
type
tare
gross weight
current Km
register date
Acquisition Date
Maintenance/Checkup Frequency (in Kms)
}

class Organization {
name
vatNumber
website
phoneNumber
email
}



Organization "1" - "*" Vehicle: has >
Vehicle "*"- "*" VehiclesForCheckUp: contains >
VehiclesForCheckUp "*" -- "1" FM : informs >
FM "1" -- "*" VehiclesForCheckUp: selects >



@enduml