@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":CreateJobUI" as UI
participant ":CreateJobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobCategoryRepository:\nJobCategoryRepository" as JobCategoryRepository
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG


activate HRM


HRM -> UI : asks to add a new job

activate UI

UI -> CTRL** : create
activate CTRL

UI -> CTRL : getJobList()
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getJobListRepository()
activate PLAT

PLAT --> CTRL: jobCategoryRepository
deactivate PLAT

CTRL -> JobCategoryRepository : getJobList()
activate JobCategoryRepository

JobCategoryRepository --> CTRL : jobList
deactivate JobCategoryRepository

deactivate CTRL
CTRL --> UI : jobList




UI --> HRM : Displays the interface for entering the job's name
deactivate UI

HRM -> UI : Provides a job
activate UI



UI -> CTRL : createJob(reference,name)
activate CTRL



CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getJobListRepository()
activate PLAT

PLAT -> CTRL : jobListRepository
deactivate PLAT

CTRL -> JobCategoryRepository : getTaskCategoryByDescription(taskCategoryDescription)
activate JobCategoryRepository

JobCategoryRepository --> CTRL : jobList
deactivate JobCategoryRepository

deactivate CTRL
CTRL --> PLAT : jobList



CTRL -> OrganizationRepository: createJob(name)
deactivate CTRL

activate OrganizationRepository

ref over OrganizationRepository
           Validating job name
end





    OrganizationRepository --> OrganizationRepository
deactivate OrganizationRepository

OrganizationRepository --> CTRL : job

deactivate OrganizationRepository

activate CTRL
CTRL --> UI: job
deactivate CTRL
UI --> HRM: displays operation success
deactivate UI


deactivate HRM

@enduml
