'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction


class Job {
    - String jobName
    - isValidJobName(jobName)
    + Job(jobName)
}


class JobRepository {
    - List<Job> jobList
    + registerJob(jobName)
    + add(job)
    - addJob(job)
    - validate(job)
    - jobNotContains(job)
}


class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getJobRepository()
}

class RegisterJobController {
    - JobRepository jobRepository
    + RegisterJobController()
    + registerJob(jobName)
    - getJobRepository()
}

class RegisterJobUI {
}

Repositories --> Repositories : instance

RegisterJobUI .> RegisterJobController

RegisterJobController ..> Repositories : repositories

Repositories --> "1" JobRepository

RegisterJobController --> JobRepository : jobRepository

JobRepository "1" --> "*" Job : register
