@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant "System" as System
participant ":CreateJobUI" as UI
participant ":CreateJobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobRepository:\nJobRepository" as jobRepository
participant ":Job" as Job

HRM -> System : Asks to add a new job
activate System

System -> UI : Asks for the interface
activate UI

UI -> HRM : Displays the interface for entering the job's name
HRM -> UI : Provides the job's name

UI -> CTRL : CreateJob(name)
activate CTRL

CTRL -> UI : ValidateNameCriteria(name)
deactivate CTRL

UI -> PLAT : GetJobRepository()
activate PLAT

PLAT --> UI : jobRepository
deactivate PLAT

UI -> jobRepository : AddJob(name)
activate jobRepository

jobRepository --> UI : Job added successfully
deactivate jobRepository

UI -> System : Provides job name
deactivate UI

System -> Job : CreateJob(name)
activate Job

Job --> System : Job created successfully
deactivate Job

System --> HRM : Confirms the success of the operation.
deactivate System

@enduml
