@startuml
title Validating the Job Name (CTRL)

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateJobController" as CTRL

group Validating Job name
activate CTRL
CTRL -> CTRL : getJobList()
CTRL -> CTRL : validateJobName(name)
end
@enduml
