@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant "System" as System
participant ":CreateJobUI" as UI
participant ":CreateJobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobRepository:\nJobRepository" as jobRepository
participant ":Job" as Job

HRM -> System : Asks to add a new job
activate System


activate UI
ref over System, UI : Displaying Job Interface (UI)

HRM -> UI : Provides the job's name

deactivate UI


ref over UI, CTRL : Validating job name
ref over UI, PLAT, jobRepository :  Adding Job to Repository



UI -> System : Provides job name
activate UI
deactivate UI
activate "System"

System -> Job : CreateJob(name)
activate Job

Job --> System : Job created successfully
deactivate Job

System --> HRM : Confirms the success of the operation.
deactivate System

@enduml
