@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":RegisterJobUI" as UI
participant ":RegisterJobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobRepository\n:JobRepository" as jobRepository
participant "job\n:Job" as EMPREGO

activate HRM

        HRM -> UI : asks to register a new job


        activate UI

        UI -> CTRL** : create


loop for every skill
            UI --> HRM : request data (jobName)
        deactivate UI


    HRM -> UI : types requested data (jobName)
    activate UI

        UI --> HRM : show all data registered  for confirmation
        deactivate UI

        HRM -> UI : submits data
            activate UI


            UI -> CTRL : registerJob(jobName)
            activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getJobRepository()
            activate PLAT

            PLAT --> CTRL: jobRepository
            deactivate PLAT

                CTRL -> jobRepository: registerJob(jobName)
                deactivate CTRL
                activate jobRepository



                jobRepository -> EMPREGO**: register(jobName)

                activate EMPREGO

                    EMPREGO -> EMPREGO : validateJobName(jobName)
                    activate EMPREGO
                        EMPREGO --> EMPREGO
                deactivate EMPREGO
                                    jobRepository -> jobRepository: addJob(job)
                deactivate EMPREGO
                                    activate jobRepository
                                        jobRepository -> jobRepository: validateJob(job)

                                        activate jobRepository
                                            jobRepository --> jobRepository
                                        deactivate jobRepository

                                        jobRepository --> jobRepository
                                    deactivate jobRepository

                                    jobRepository --> CTRL : job
                                    deactivate jobRepository
                                    activate CTRL

                CTRL --> UI: job
                deactivate CTRL
                UI --> HRM: displays the success of the operation.
end
        deactivate UI
    deactivate HRM

@enduml