@startuml
title Displaying Job Interface (UI)

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "Human Resources Manager" as HRM
participant "System" as System
participant ":CreateJobUI" as UI

group Job Interface
autonumber 2
"System" -> UI : Asks for the interface
activate UI

UI -> HRM : Displays the interface for entering the job's name
deactivate UI
end

@enduml
