@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":RegisterJobUI" as UI
participant ":RegisterJobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobListRepository\n:jobListRepository" as jobRepository
participant "job\n:Job" as EMPREGO

activate HRM

HRM -> UI : asks to register a new job
activate UI

UI -> CTRL** : register
activate CTRL

UI -> CTRL : getJobList()
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getJobRepository()
activate PLAT

PLAT --> CTRL: jobListRepository
deactivate PLAT

CTRL -> jobRepository : getJobList()
activate jobRepository

jobRepository --> CTRL : jobList
deactivate jobRepository

CTRL --> UI : jobList
deactivate CTRL

UI --> HRM : shows job list
UI --> HRM : types requested data (name)
deactivate UI

HRM -> UI : asks to leave
activate UI

UI --> HRM : asks operation confirmation


HRM -> UI : confirms operation
deactivate UI

deactivate HRM

@enduml
