@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":GenerateTeamUI" as UI
participant ":GenerateTeamController" as CTRL
participant ":Team" as Team
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "CollaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository
participant "SkillRepository:\nSkillRepository" as SkillRepository


activate HRM

        HRM -> UI : asks to generate a new team

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : generate

            UI -> CTRL : getSkills()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getSkillsRepository()
                activate PLAT

                    PLAT --> CTRL: SkillRepository
                deactivate PLAT

                CTRL -> SkillRepository : getSkills()
                activate SkillRepository

                    SkillRepository --> CTRL : SkillRepositoryList
                deactivate SkillRepository

                CTRL --> UI : SkillRepositoryList
            deactivate CTRL

            UI --> HRM : shows skills list\n and asks to select one
        deactivate UI

    loop [for each skill
        HRM -> UI : selects a skill
        activate UI

            UI --> HRM : requests data
        deactivate UI

        HRM -> UI : types requested data (minimumCollaborators, maximumCollaborators)
        activate UI

            UI --> HRM : shows typed data
        deactivate UI

    end


    HRM -> UI : confirms and submits data
    activate UI

        UI -> CTRL : createTeam(skills, minimumCollaborators, maximumCollaborators)
        deactivate UI

        activate CTRL

            CTRL -> Team : teamCreation(skills, minimumCollaborators, maximumCollaborators)
        deactivate CTRL

        activate Team


                Team -> RepositorySingleton : getInstance()
                activate Team

                    activate RepositorySingleton

                        RepositorySingleton --> Team: repositories
                    deactivate RepositorySingleton

                    Team -> PLAT : getCollaboratorRepository()
                    activate PLAT

                        PLAT -> Team : CollaboratorRepository
                    deactivate PLAT

                    loop for each Collaborator
                        Team -> CollaboratorRepository : getCollaboratorBySkill(skills)
                        activate CollaboratorRepository

                            CollaboratorRepository -> SkillRepository : getSkillsOfCollaborator(skills)
                            activate SkillRepository

                                SkillRepository -> CollaboratorRepository : true/false
                            deactivate SkillRepository

                            CollaboratorRepository --> Team : true/false
                        deactivate CollaboratorRepository
                        Team --> Team : addCollaborator(Collaborator)
                    deactivate Team
                    end


                    Team --> CTRL : Team Proposal
            deactivate Team


        activate CTRL


            CTRL -> UI : Team Proposal
            deactivate CTRL

        activate UI

            UI -> HRM: Show team and ask for confirmation
            deactivate UI
            alt accept team proposal


                HRM -> UI : accept team
                activate UI

                UI -> CTRL : acceptTeamCreation()
                deactivate UI
                activate CTRL

                CTRL -> Team : acceptTeamCreation()
                activate Team

                Team -> CTRL : teamCreationSuccessful
                deactivate Team
                CTRL -> UI : team creation successful
                deactivate CTRL
                activate UI

                UI -> HRM : team creation successful
                deactivate UI
            else refuse team proposal
               HRM -> UI : refuse team
               activate UI

               UI -> CTRL : rejectTeamCreation()
               deactivate UI

               activate CTRL

               CTRL -> Team : rejectTeamCreation()
               activate Team

               Team -> CTRL : team deleted
               deactivate Team
               CTRL -> UI : teamDeleteSuccessful
               deactivate CTRL
               activate UI

               UI -> HRM : team delete successful
               deactivate UI
            end
    deactivate UI

deactivate HRM

@enduml