@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":Team" as Team
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "CollaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository
participant "SkillRepository:\nSkillRepository" as SkillRepository


autonumber 14
-> Team : teamCreation(skills, minimumCollaborators, maximumCollaborators)
autonumber 14.1

        group Generate Team

        activate Team

                Team -> RepositorySingleton : getInstance()
                activate Team

                    activate RepositorySingleton

                        RepositorySingleton --> Team: repositories
                    deactivate RepositorySingleton

                    Team -> PLAT : getCollaboratorRepository()
                    activate PLAT

                        PLAT -> Team : CollaboratorRepository
                    deactivate PLAT

                    loop for each Collaborator
                        Team -> CollaboratorRepository : getCollaboratorBySkill(skills)
                        activate CollaboratorRepository

                            CollaboratorRepository -> SkillRepository : getSkillsOfCollaborator(skills)
                            activate SkillRepository

                                SkillRepository -> CollaboratorRepository : true/false
                            deactivate SkillRepository

                            CollaboratorRepository --> Team : true/false
                        deactivate CollaboratorRepository
                        Team --> Team : addCollaborator(Collaborator)
                    deactivate Team
                    end

                end
            deactivate Team




@enduml