@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":GenerateTeamUI" as UI
participant ":GenerateTeamController" as CTRL
participant ":Team" as Team
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "CollaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository
participant "TeamRepository:\nTeamRepository" as TeamRepository
participant "skillRepository\n:SkillRepository" as SkillRepository


activate HRM

        HRM -> UI : asks to generate a new team

        activate UI

            UI -> CTRL** : create

            UI -> CTRL : getSkillList()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton


                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getSkillsRepository()
                activate PLAT

                    PLAT --> CTRL: SkillRepository
                deactivate PLAT

                CTRL -> SkillRepository : getSkillList()
                activate SkillRepository

                    SkillRepository --> CTRL : SkillList
                deactivate SkillRepository

                CTRL --> UI : SkillList
            deactivate CTRL

            UI --> HRM : shows skills list\n and asks to select one
        deactivate UI

    loop [for each skill
        HRM -> UI : selects a skill
        activate UI
    end

            UI --> HRM : requests data (minimumCollaborators, maximumCollaborators)
        deactivate UI

        HRM -> UI : types requested data
        activate UI

            UI --> HRM : shows typed data
        deactivate UI




    HRM -> UI : confirms and submits data
    activate UI

        UI -> CTRL : generateTeam(skill, minimumCollaborators, maximumCollaborators)
        deactivate UI

        activate CTRL

            CTRL -> Team : generateTeam(skill, minimumCollaborators, maximumCollaborators)

        activate Team


                    Team -> RepositorySingleton : getInstance()

                    activate RepositorySingleton


                        RepositorySingleton --> Team: repositories
                    deactivate RepositorySingleton

                    Team -> PLAT : getCollaboratorRepository()
                    activate PLAT

                        PLAT --> Team : CollaboratorRepository
                    deactivate PLAT

                    loop while minCollabo <= encontrados <= maxCollabo
                        Team -> CollaboratorRepository : getCollaboratorBySkill(skills)
                        activate Team
                        activate CollaboratorRepository

                        CollaboratorRepository -> CollaboratorRepository : findCollaborator(skills)
                        activate CollaboratorRepository
                        CollaboratorRepository --> CollaboratorRepository: collaborator
                        deactivate CollaboratorRepository



                            CollaboratorRepository --> Team : collaborator
                        deactivate CollaboratorRepository
                        Team --> Team : addCollaborator(Collaborator)
                        deactivate Team

                    end



                    Team --> CTRL : Team Proposal

            deactivate Team




            CTRL -> UI : Team Proposal
            deactivate CTRL

        activate UI

            UI -> HRM: Show team and ask for confirmation
            deactivate UI
            alt accept team proposal


                HRM -> UI : accept team
                activate UI

                UI -> CTRL : acceptTeamCreation()
                deactivate UI
                activate CTRL

                CTRL -> Team : acceptTeamCreation()

                activate Team

                     Team -> RepositorySingleton : getInstance()
                     activate RepositorySingleton

                        RepositorySingleton --> Team: repositories
                     deactivate RepositorySingleton


                    Team -> PLAT : getTeamRepository()
                    activate PLAT

                    PLAT --> Team : teamRepository
                    deactivate PLAT


                    Team -> TeamRepository : addTeam()
                    activate Team
                    activate TeamRepository
                    TeamRepository --> TeamRepository : addTeam()
                    activate TeamRepository
                    TeamRepository --> TeamRepository :
                    deactivate TeamRepository




                    TeamRepository -> Team : teamAdded
                    deactivate TeamRepository
                    Team --> Team
                    deactivate Team

                Team -> CTRL : teamCreationSuccessful
                    deactivate Team
                CTRL -> UI : team creation successful
                deactivate CTRL
                activate UI

                UI -> HRM : team creation successful
                deactivate UI
            else refuse team proposal
               HRM -> UI : refuse team
               activate UI

               UI -> CTRL : rejectTeamCreation()
               deactivate UI

               activate CTRL

               CTRL -> Team : rejectTeamCreation()
               activate Team

                Team -> Team : rejectTeamCreation()
               activate Team
               Team --> Team
               deactivate Team

               Team -> CTRL : teamDeleteSuccessful
               deactivate Team
               CTRL -> UI : teamDeleteSuccessful
               deactivate CTRL
               activate UI

               UI -> HRM : team delete successful
               deactivate UI
            end
    deactivate UI

deactivate HRM

@enduml