@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Fleet\nManager" as FM
participant ":System" as System

activate FM

    FM -> System : Accesses the fleet management system.
    activate System

    System -> FM : Provides the FM the option to insert the range of kilometers needed for check-up.
        deactivate System

        System --> FM : Provides the option to set a number of kms the user wants to be informed before reaching the overhauling limit
    activate System

    System -> FM : Provides a list of vehicles (and all their info) that need check-up.
    deactivate System

        System --> FM : Displays operation success
    activate System

@enduml