@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Fleet\nManager" as FM
participant ":System" as System

activate FM

    FM -> System : Accesses the fleet management system.
    activate System

    System -> FM : Provides the FM the option to insert the range of kilometers needed for check-up.
        deactivate System

        System --> FM : Provides the option to set a number of kms the user wants to be informed before reaching the overhauling limit
    activate System

    System -> FM : Does not provide a list of vehicles (no vehicles in the system or non ilegible vehicles to a check-up)
    deactivate System

        System --> FM : Displays operation success
    activate System

@enduml