@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Fleet\nManager" as FM
participant ":System" as System

activate FM

    FM -> System : Fleet manager accesses the fleet management system.
    activate System

    System -> FM : The system gives the FM the option to insert the range of kilometers needed for overhauling.
        deactivate System

        System --> FM : The system gives the option to set a number of kms to warn the user when current kilometers are close to limit value
    activate System

    System -> FM : The system provides an option to view vehicles that need inspection.
    deactivate System

        FM --> System : FM selects the vehicles for inspection
    activate System

    System -> FM : The system displays selected vehicles’ details (kms, plate, brand…)
    deactivate System

        FM --> System : FM confirms (or not) the initialization of the overhaul process for selected vehicles.
    activate System

    System -> FM : confirms data
    deactivate System

        System --> FM : displays operation success
    activate System

@enduml