@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "HRM" as Employee
participant ":System" as System


activate Employee

    Employee -> System : ask to register a skill
    activate System

        System --> Employee : request data (name)
    deactivate System

    Employee -> System : types requested data (name)

    activate System

        System --> Employee : shows requested data
    deactivate System

    Employee -> System : submit data
    activate System

        System --> Employee :shows operation success
    deactivate System

@enduml