@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : Accesses the human resources management system.
    activate System

    System --> HRM : Displays the employee’s details, including their current skills (if any).
    deactivate System

     HRM -> System : Selects the option to edit the employee’s skills.
    activate System

        System --> HRM : Presents a list of available skills.
    deactivate System

        HRM -> System : Selects one or more skills from the list.
    activate System

    System --> HRM : Displays all the changes.
    deactivate System

    HRM --> System : Confirms the selection.
    activate System

    System --> HRM : Validates and stores it.


    System --> HRM : Confirms the success of the operation.
    deactivate System




@enduml