@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "FM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Start a request to register a vehicle/machine/equipment
    activate System

        System --> Employee : Request data (Brand,Model,Type...)
    deactivate System

    Employee -> System : Types requested data
    activate System

        System --> Employee : Show all data registed and requests for confirmation
    deactivate System

    Employee -> System : Confirms data
    activate System

        System --> Employee : Displays operation success
    deactivate System

@enduml