ººº@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : request to register a vehicle
    activate System

    |||
    group requested data

    System --> Employee : request vehicle plate ID
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : request vehicle brand
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : request vehicle model
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : request vehicle type
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : request vehicle Tare Weight
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : request vehicle Gross Weight
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : request vehicle millage
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : request vehicle register date
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : request vehicle acquisition date
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : request vehicle maintenance frequency
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : request vehicle last checkup
    deactivate System

    Employee -> System : types requested data
    activate System

    end
    |||


        System --> Employee : show all data registered  for confirmation
    deactivate System

    Employee -> System : submits data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml