@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "FM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : request to register a vehicle/machine/equipment
    activate System

        System --> Employee : request data (Brand,Model,Type...)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : show all data registed and requests for confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : cisplays operation success
    deactivate System

@enduml