@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space Manager" as Employee
participant ":System" as System


activate Employee

    Employee -> System : ask to add a new entry to the To-Do List
    activate System

        System --> Employee : shows green spaces list
    deactivate System

    Employee -> System : chooses a green space from the list

    activate System

        System --> Employee : request data (title, description, urgency, expectedDuration)
    deactivate System

     Employee -> System : types requested data

     activate System

     System --> Employee : show all data registered\n and the confirmation menu
     deactivate System

    Employee -> System : submits data
    activate System

        System --> Employee : shows operation (in)success
    deactivate System

@enduml