@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Fleet Manager" as FM

participant ":CheckupListUI" as UI
participant ":VehicleListController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository\n:VehicleRepository" as vehicleRepository

activate FM

FM -> UI : Asks to generate a list of vehicles needing check-up
activate UI

UI -> CTRL** : create

UI -> CTRL : getVehicleListNeedingCheckup()

deactivate UI

activate CTRL
CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getVehicleRepository()
activate PLAT

PLAT --> CTRL: vehicleRepository
deactivate PLAT

CTRL -> vehicleRepository : getVehiclesNeedingCheckup()

activate vehicleRepository



activate vehicleRepository

loop for each vehicle in vehicleList
    vehicleRepository -> vehicleRepository : needsCheckup(vehicle)
    activate vehicleRepository
    vehicleRepository --> vehicleRepository : true/false
    deactivate vehicleRepository



deactivate vehicleRepository
end


activate vehicleRepository


vehicleRepository --> CTRL : vehiclesNeedingCheckup
deactivate vehicleRepository



CTRL --> UI : vehiclesNeedingCheckup
deactivate CTRL
activate UI
UI --> FM : Provides a list of vehicles that need check-up (and all their info)
deactivate UI
deactivate FM

deactivate FM

@enduml
