@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
skinparam classAttributeIconSize 0
'left to right direction




class VehicleRepository {
    - List<Vehicle> vehicleList
    + requestList(activation)
    - getVehiclesNeedingCheckUp(activation)
    - checkUpListCreated()
}



class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
}

class VehicleListController {
    + VehicleListController()
    + requestList(activation)
}

class CheckUpListUI {
}

CheckUpListUI .> VehicleListController

VehicleListController .> Repositories : repositories
Repositories  --> "1 " VehicleRepository
Repositories -> Repositories : instance

VehicleListController ..>  VehicleRepository : vehicleRepository


@enduml