@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant "vehicleRepository\n:VehicleRepository" as vehicleRepository


autonumber 8

 -> vehicleRepository : getVehiclesNeedingCheckup()
autonumber 3.1
activate vehicleRepository
    group Generate CheckUp List

            loop for each vehicle in vehicleList
                vehicleRepository -> vehicleRepository : needsCheckup(vehicle)
                activate vehicleRepository
                vehicleRepository --> vehicleRepository : true/false
                deactivate vehicleRepository

    end
end

@enduml