@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
skinparam classAttributeIconSize 0
'left to right direction

class VehicleRepository {
    - List<Vehicle> vehicleList
    + requestList(activation)
    - getVehiclesNeedingCheckUp(activation)
    - checkUpListCreated()
    + getVehicleCheckUpList(): List<Vehicle>
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
}

class VehicleListController {
    + VehicleListController()
    + requestList(activation)
    + receiveVehicleList(List<Vehicle>)
    + sendVehicleListToUI(List<Vehicle>)
}

class CheckUpListUI {
    + displayVehicleList(List<Vehicle>)
}

CheckUpListUI ..> VehicleListController

VehicleListController --> CheckUpListUI : sendVehicleListToUI()
VehicleListController .> Repositories : repositories
Repositories  --> "1 " VehicleRepository
Repositories -> Repositories : instance
VehicleListController ..>  VehicleRepository : vehicleRepository
VehicleRepository -> VehicleListController : getVehicleCheckUpList()
@enduml
