@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space\nManager" as gsm
participant ":System" as System

        activate gsm

        gsm --> System: Introduce the file "WaterUsed.csv" with information.
        activate System

        System -> gsm : Provides a list of vehicles that need check-up (and all their info)
        System --> gsm : Displays operation success

        deactivate System
        deactivate gsm
@enduml