@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space\nManager" as gsm
participant ":System" as System

        activate gsm

        gsm -> System: Introduce the file "WaterUsed.csv" with information.
        activate System

        System -> gsm: Ask for inputs (time period,park identification...)
        gsm -> System : Introduce data
        System -> System : confirms data
        System -> System : Read and interpret data from "WaterUsed.csv"
        System -> System: Perform statistical analysis
        System -> System: Calculate average monthly costs
        System -> System: Identify parks with highest and lowest consumption
        System --> gsm: costs referring to water consumption
        System --> gsm: Display barplot of monthly water consumption
        System --> gsm: Provide average monthly costs
        System --> gsm: Present statistical indicators for parks

        deactivate System
        deactivate gsm
@enduml