@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : HRM accesses the human resources management system.
    activate System

        System --> HRM : The system displays the interface for entering all the possible employee’s jobs
    deactivate System

     HRM -> System : HRM selects the option to add a new job to the job’s collection
    activate System

        HRM -> System : HRM provides the profession(s)
    deactivate System

    System --> HRM : The system stores all the data.
    activate System

        System --> HRM : The system confirms the success of the operation.
    deactivate System



@enduml