@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM


     HRM -> System : HRM selects the option to add a new job
    activate System

        System --> HRM : The system displays the interface for entering the job's name
    deactivate System

        HRM -> System : HRM provides the profession(s)
    activate System

        System --> HRM : The system confirms the success of the operation.
    deactivate System



@enduml