@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":RegisterSkillUI" as UI
participant ":RegisterSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillListRepository\n:skillListRepository" as skillRepository
participant "skill\n:Skill" as EMPREGO

activate HRM

        HRM -> UI : asks to register a new skill

        activate UI

            UI -> CTRL** : register

            UI -> CTRL : getSkillList()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getSkillRepository()
                activate PLAT

                    PLAT --> CTRL: skillListRepository
                deactivate PLAT

                CTRL -> skillRepository : getSkillList()
                activate skillRepository

                    skillRepository --> CTRL : skillList
                deactivate skillRepository

                CTRL --> UI : skillList
            deactivate CTRL




            UI --> HRM : show skill list
            UI --> HRM : request data (name)
        deactivate UI


    HRM -> UI : types requested data (name)
    activate UI

        UI --> HRM : shows requested data typed
        deactivate UI

        HRM -> UI : submits data
            activate UI


            UI -> CTRL : registerSkill(name)
            activate CTRL


                CTRL -> EMPREGO: registerSkill(name)
                deactivate CTRL




                    activate EMPREGO
                        EMPREGO --> EMPREGO : validateNameSkill(skill)

                        loop [for each skill name
                          EMPREGO -> EMPREGO : validateNameSkill(skill)
                            activate EMPREGO

                                 EMPREGO --> EMPREGO : true/false
                            deactivate EMPREGO
                        end


                        EMPREGO --> skillRepository : skill
                    deactivate EMPREGO

                    activate skillRepository

                    skillRepository -> skillRepository: addSkill(skill)


                    activate skillRepository
                        skillRepository -> skillRepository: validateSkill(skill)
                        activate skillRepository
                            skillRepository --> skillRepository
                        deactivate skillRepository

                        skillRepository --> skillRepository
                    deactivate skillRepository

                    skillRepository --> CTRL : skill
                     activate CTRL

                deactivate skillRepository

                CTRL --> UI: skill
                deactivate CTRL
                UI --> HRM: Confirms the (un)success of the operation.
        deactivate UI
    deactivate HRM

@enduml