@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Alternative One

autonumber

actor "HRM" as Employee
participant ":RegisterSkillUI" as UI
participant ":RegisterSkillController" as CTRL
participant "organization\n:Organization" as ORG
participant "skill\n:Skill" as SKILL

activate Employee

    Employee -> UI : ask to register a skill
    activate UI


    UI --> CTRL** : register


    UI --> Employee : request data (name)
    deactivate UI

    Employee -> UI : types requested data (name)

    activate UI

    UI --> Employee : shows requested data

    deactivate UI

    Employee -> UI : submit data

    activate UI

    UI --> CTRL :  registerSkill(name)
    activate CTRL

        CTRL --> ORG :  registerSkill(name)

        activate ORG

        ORG --> SKILL** :  registerSkill(name)


        ORG -> ORG : addSkill (skill)
        activate ORG
        ORG --> ORG :
'        ORG -> ORG : validateSkill (skill)

        deactivate ORG

                ORG --> CTRL : skill
        deactivate ORG

        CTRL --> UI : skill



    deactivate CTRL

    UI --> Employee :shows operation success
    deactivate UI


note right of SKILL
        Skill constructor
        normally validates
        arguments.
    end note


@enduml
