@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillListRepository:\nskillListRepository" as SkillListRepository

autonumber 12
-> CTRL : registerSkill(name)

autonumber 12.1

activate CTRL
    group Get Skill List
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getSkillListRepository()
        activate PLAT

            PLAT -> CTRL : SkillListRepository
        deactivate PLAT

        CTRL -> SkillListRepository : getSkillList
        activate SkillListRepository

            SkillListRepository --> CTRL : SkillList
        deactivate SkillListRepository

    end group

    autonumber 13
    <-- CTRL : SkillList

deactivate CTRL


@enduml