@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Fleet Manager" as Colab

participant ":RetrieveTasksUI" as UI
participant ":TeamController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "teamRepository\n:TeamRepository" as teamRepository

activate Colab

Colab -> UI : Asks to generate a list of tasks assigned to the collaborator
activate UI
UI --> Colab : Asks the start and end dates
Colab -> UI : Provides the dates
    UI --> Colab : Asks the collaborator taxpayer number
    Colab -> UI : Provides the taxpayer number

UI -> CTRL** : create

UI -> CTRL : requestColabTaskList()

deactivate UI

activate CTRL




ref over CTRL, RepositorySingleton, PLAT : Get Team Repository

CTRL -> teamRepository : requestColabTaskList()

 activate teamRepository
    ref over teamRepository : Generate Task List





teamRepository --> CTRL : colabTaskList
deactivate teamRepository

CTRL --> UI : colabTaskList
deactivate CTRL
activate UI
UI --> Colab : Provides the list of tasks
deactivate UI
deactivate Colab

@enduml
