@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant "teamRepository\n:TeamRepository" as teamRepository


autonumber 12

 -> teamRepository : requestColabTaskList()
autonumber 12.1
activate teamRepository
    group Generate Tasks List

            loop for each vehicle in vehicleList
                teamRepository -> teamRepository :getTeamByColabTaxNumber()
                activate teamRepository
                teamRepository --> teamRepository : true/false
                deactivate teamRepository

    end
    teamRepository --> teamRepository : getColabTasksBetweenDates()

end

@enduml