@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Collaborator" as Colab

participant ":RetrieveTasksUI" as UI
participant AgendaController as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agenda\n:Agenda" as agenda

activate Colab

Colab -> UI : Asks to generate a list of tasks assigned to the collaborator
activate UI
UI --> Colab : Asks the start and end dates
Colab -> UI : Provides the dates
    UI --> Colab : Asks the collaborator taxpayer number
    Colab -> UI : Provides the taxpayer number

UI -> CTRL** : create

UI -> CTRL : requestColabTaskList()

deactivate UI

activate CTRL
CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getTeamRepository()
activate PLAT

PLAT --> CTRL: agenda
deactivate PLAT

CTRL -> agenda : requestColabTaskList()

activate agenda



activate agenda

loop for each team in teamList
    agenda -> agenda : getTeamByColabTaxNumber()
    activate agenda


    agenda --> agenda : true/false
    deactivate agenda



deactivate agenda
end



    agenda --> agenda : getColabTasksBetweenDates()




agenda --> CTRL : colabTaskList
deactivate agenda



CTRL --> UI : ColabTaskList
deactivate CTRL
activate UI
UI --> Colab : Provides the list of tasks
deactivate UI
deactivate Colab

deactivate Colab

@enduml
