@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho


left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model




'  #########    General Information's      ##########
    class GSM {
    }

    class GreenSpace {
    }





   class Agenda {
            List<AgendaEntry>
   }

   class AgendaEntry {
            toDoEntry
            StartingDate
            EndDate
            Team
            List<Vehicles>

   }

    class ToDoEntry {
             greenSpace
             title
             description
             urgency
             expectedDuration
    }

    class SortGreenSpaces {
        sortMethod
    }


    GSM "1" -- "1..*" GreenSpace : registers >
    GSM "1" -- "1..*" ToDoEntry : registers >
    GSM "1" -- "*" AgendaEntry : register entry >
    GSM "1" -- "*" AgendaEntry : Assigns a team >
    GSM "1" -- "*" AgendaEntry : postpone entry >
    GSM "1" -- "*" AgendaEntry : cancel entry >
    GSM "1" -- "1..*" Vehicle : assigns >
    GSM "1" -- "1" SortGreenSpaces : lists managed green spaces >
    SortGreenSpaces "1" -- "*" GreenSpace : get >
    AgendaEntry "1  " -- "1..*"  Vehicle  : has >
    AgendaEntry "1" -- "1" Team : posses >
    Agenda "1" - "*" AgendaEntry : has >
    AgendaEntry "1" - "1" ToDoEntry : has >






'  #########          ##########



'  #########    VFM      ##########

    class VFM {
    }

    class Vehicle {
         plateID
         brand
         model
         type
         tare
         grossWeight
         millage
         registerDate
         acquisitionDate
         maintenanceFrequency
         lastCheckUp
    }



    class CheckUp {
        licence
        date
        currentMileage
    }


    VFM "1" -- "*" Vehicle : register >
    VFM "1" -- "*" CheckUp : register >
    VFM "1" -- "*" Vehicle : lists check-up >
    CheckUp "1" -- "1..*" Vehicle : assigned >




'  #########          ##########



'  #########    HRM      ##########

    class HRM {
    }

    class Collaborator {
        name
        birthdate
        admissionDate
        address
        phoneNumber
        email
        taxpayerNumber
        id_doc_type
        id_doc_number
    }

    class Team {
        skill
        minTeamSize
        maxTeamSize
    }

    class Skill {
        name
    }

    class Job {
        name
    }

    HRM "1" -- "1..*" Skill : register >
'    HRM "1" -- "*" Skill : assignes >
    HRM "1" -- "1..*" Job : register >
    HRM "1" - "1..*" Collaborator : register >
    HRM "1" -- "1..*" Team : generates >

    Skill "1.." -- "*" Collaborator : assigned to >

    Collaborator "1" -- "*" Job : has >

    Team "1" -- "1..*" Collaborator : has >

Collaborator "1" -- "*" ToDoEntry : lists >
Collaborator "1" -- "1" ToDoEntry : registers task completion >
Agenda "1" -- "*" ToDoEntry : has >

'  #########          ##########

'  #########    General Associations     ##########

    Team "*" -- "*" Vehicle : uses >
    Team "1..*" - "*" Agenda : has >






'  #########          ##########

@enduml