@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Domain Model - US004

hide circles
hide methods

package "HR System" {

    class HRM {
    }

    class Employee {
        skill
    }

    class ListAvailableSkills {
        List<Skills>
        }

    HRM "1" - "1" Employee : selects >
    Employee "1  " --- "1" ListAvailableSkills : shows >
     HRM "1" --- "1  " ListAvailableSkills : selects >

}



@enduml

