@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor pink
}

title Use Case Diagram

left to right direction



    actor "Human Resources Manager" as HRM
    actor "Vehicles and Fleet Manager" as FM
    actor "Green Spaces Manager" as GSM
    actor "Software Quality Assessment Team Manager" as QAM
    actor "Collaborator" as COL






rectangle "Use Cases" as usecases{
    usecase "UC1 - Registering skills for collaborators" as UC1
    usecase "UC2 - Profession registration" as UC2
    usecase "UC3 - Register a collaborator with a job and fundamental characteristics" as UC3
    usecase "UC4 - Assigning skills to a collaborator" as UC4
    usecase "UC5 - Generate a team proposal automatically" as UC5
    usecase "UC6 - Registering Vehicles" as UC6
    usecase "UC7 - Register the check-up of a vehicle" as UC7
    usecase "UC8 - Check-up of vehicles" as UC8
    usecase "UC9 - Water consumption of green spaces" as UC9
    usecase "UC10 - Equipment Preferences" as UC10
    usecase "UC11 - Collect data from the user portal about the use of the park" as UC11
    usecase "UC12 - Importing Water Point Routes and Installation Costs" as UC12
    usecase "UC13 - Optimizing irrigation" as UC13
    usecase "UC14 - Running Asymptotic Behavior Tests" as UC14
    usecase "UC17 - TITLE" as UC17
    usecase "UC18 - TITLE" as UC18
    usecase "UC19 - TITLE" as UC19
    usecase "UC20 - Register a Green Space" as UC20
    usecase "UC21 - Adding a To-Do List Entry for Green Space Management" as UC21
    usecase "UC22 - Add a new entry in the Agenda" as UC22
    usecase "UC23 - Assign a Team to an entry in the Agenda" as UC23
    usecase "UC24 - Postpone task in Agenda" as UC24
    usecase "UC25 - Overhauling of vehicles" as UC25
    usecase "UC26 - Assign One or More Vehicles to Agenda Entry" as UC26
    usecase "UC27 - Show an organized list of all green spaces managed by manager" as UC27
    usecase "UC28 - Consult the tasks assigned to me between two dates." as UC28
    usecase "UC29 - Record the completion of a task." as UC29

    HRM --> UC1
    HRM --> UC2
    HRM --> UC3
    HRM --> UC4
    HRM --> UC5
    FM --> UC6
    FM --> UC7
    FM --> UC8
    GSM --> UC9
    GSM --> UC10
    GSM --> UC11
    GSM --> UC12
    GSM --> UC13
    QAM --> UC14
    GSM --> UC17
    GSM --> UC18
    QAM -> UC19
    GSM --> UC20
    GSM --> UC21
    GSM --> UC22
    GSM --> UC23
    GSM --> UC24
    GSM --> UC25
    GSM --> UC26
    GSM --> UC27
    COL -> UC28
    COL -> UC29

}


@enduml