@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
participant ":RegisterGreenSpaceController" as CTRL
participant ":GreenSpace" as greenSpaceRepository
participant ":Size" as EMPREGO
autonumber 3


 -> CTRL :getGreenSpacesSizes()
autonumber 3.1
activate CTRL
    group Get Sizes List
            CTRL ->  greenSpaceRepository : GreenSpace
            activate greenSpaceRepository

                greenSpaceRepository -> EMPREGO: Size
                activate EMPREGO
                    EMPREGO -> EMPREGO : values()

                EMPREGO --> greenSpaceRepository : sizeList
                deactivate EMPREGO
                greenSpaceRepository --> CTRL : sizeList
            deactivate greenSpaceRepository

    end
            <-- CTRL : sizeList
    autonumber 4
deactivate CTRL


@enduml