@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterGreenSpaceController" as CTRL
participant "repositories\n:Repositories" as PLAT
participant "authenticationRepository\n:AuthenticationRepository" as authenticationRepository

autonumber 16

autonumber 16.1
activate CTRL

       CTRL -> CTRL : registerGreenSpace(name,size,area)
           activate CTRL
              CTRL -> CTRL : getResponsible()
                     activate CTRL
    group Get Responsible

                        CTRL -> PLAT  : getAuthenticationRepository()
                        activate PLAT

                        PLAT --> CTRL : authenticationRepository
                        deactivate PLAT

                        CTRL -> authenticationRepository : getCurrentUserSession()
                        activate authenticationRepository

                            authenticationRepository --> CTRL : currentUserSession
                        deactivate authenticationRepository

                        CTRL -> UserSession : getUserId()
                        activate UserSession

                            UserSession --> CTRL : userSession
                        deactivate UserSession

                        CTRL -> Email : getEmail()
                        activate Email

                            Email --> CTRL : email
                        deactivate Email
                    CTRL --> CTRL : email
                    deactivate CTRL
    end

autonumber 17
deactivate CTRL

    CTRL ->  : registerGreenSpace(name,size,area,email)


@enduml