@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "greenSpaceRepository:\n:GreenSpaceRepository" as ORG
participant "greenSpace\n:GreenSpace" as GREENSPACE

autonumber 16
-> ORG: registerGreenSpace(name,size,area,responsible)

autonumber 16.1
activate ORG
    group Register Green Space

        ORG -> GREENSPACE: create



        ORG -> ORG: addGreenSpace(greenSpace)
        deactivate GREENSPACE

        activate ORG
            ORG -> ORG: validate(greenSpace)
            activate ORG
                ORG --> ORG
            deactivate ORG

            ORG --> ORG
        deactivate ORG
    end

    autonumber 17
    <-- ORG : greenSpace
deactivate ORG


@enduml