@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space Manager" as User
participant ":System" as System

User -> System : asks to record the equipments used
    activate System

System --> User : shows a list of equipments that were available
    deactivate System

User -> System : selects zero or more equipments used that day
    activate System

System --> User : asks if they want a file that has the recording of the last 1000 users choices of equipments or a pie chart that represents, in percentage, the use of each piece of equipment
    deactivate System

User -> System : requests file
    activate System

System --> User : sends the file requested
    deactivate System
@enduml