@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor pink
}

title Use Case Diagram

left to right direction

rectangle "System Actors                       " as actors {
    actor "Human Resources Manager" as HRM
    actor "Vehicles and Fleet Manager" as FM

}



rectangle "Use Cases" as usecases{
    usecase "UC1 - Registering skills for collaborators" as UC1
    usecase "UC2 - Profession registration" as UC2
    usecase "UC3 - Register a collaborator" as UC3
    usecase "UC4 - Assigning skills to a collaborator" as UC4
    usecase "UC5 - Generate a team proposal automatically" as UC5
    usecase "UC6 - Registering Vehicles" as UC6
    usecase "UC7 - Register the overhaul of a vehicle" as UC7
    usecase "UC8 - Overhauling of vehicles " as UC8
    HRM --> UC1
    HRM --> UC2
    HRM --> UC3
    HRM --> UC4
    HRM --> UC5
    FM --> UC6
    FM --> UC7
    FM --> UC8
}


@enduml