@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Collaborator" as COLLAB
participant ":System" as System


        COLLAB -> System: Asks to generate a list of tasks assigned to the collaborator
        activate COLLAB
        activate System

        System --> COLLAB : Provides a list of tasks


        deactivate System
        deactivate COLLAB
@enduml