@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

package "System" {

    class HRM {
    }

    class Skill {
        name
    }

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

    class Job {
        name
    }

    class Collaborator {
        name
        birthdate
        admissionDate
        address
        phoneNumber
        email
        taxpayerNumber
        id_doc_type
        id_doc_number

    }

    class Team {
        skill
        teamSize
    }

    class VFM {
    }

    class Vehicle {
         plateID
         brand
         model
         type
         tare
         grossWeight
         millage
         registerDate
         acquisitionDate
         maintenanceFrequency
    }

    class VehiclesForCheckUp {
        Vehicle
    }



    HRM "1  " --- "1..*" Skill : creates >
    HRM "1" - "1..*" Job : creates >
    HRM "1" - "1..*" Collaborator : creates >
    HRM "1  " - "1 " Team : generates >


    VFM "1" -- "*" Vehicle : creates >
    VFM "1" -- "*" VehiclesForCheckUp: selects >

    Skill "1..*   " -- "1..*" Collaborator : assigned >

    Organization "1" ---- "*" Skill : has >
    Organization "1" --- "1..*" Job : has >
    Organization "1" -- "1..*" Collaborator : has >
    Organization "1 " ---- "*" Team : has >

    Collaborator "1" - "1..*" Job : has >

    Team "1 " -- "1..*" Collaborator : assigned <

    Vehicle "*" -- "1" Organization : has <
    Vehicle "*"-- "*" VehiclesForCheckUp: contains >

    VehiclesForCheckUp "*" -- "1" VFM : informs >


}

@enduml