@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Collaborator" as COLAB
participant ":System" as System


        COLAB -> System: Asks to generate a list of tasks assigned to the collaborator
        activate COLAB
        activate System

        System --> COLAB: Asks to select a filter
        COLAB -> System : Selects a filter
        System --> COLAB: Asks the start and end dates
        COLAB -> System : Provides the start and end dates
        System --> COLAB: Provides the list of tasks


        deactivate System
        deactivate COLAB
@enduml