@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM


     HRM -> System : asks to register a new job
    activate System

    System --> HRM :  show jobs list
    System --> HRM :  request data (name)
    HRM -> System : types requested data (name) or asks to leave
    System --> HRM : asks data confirmation
    HRM -> System : confirms data
    System --> HRM : Confirms the (un)success of the operation.


    deactivate System
    deactivate HRM


@enduml
