@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM


     HRM -> System : Asks to add a new job
    activate System

        System --> HRM : Displays the interface for entering the job's name
    deactivate System

        HRM -> System : Provides a job
    activate System

        System --> HRM : Confirms the success of the operation.
    deactivate System



@enduml