@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Get Green Spaces by Responsible User

autonumber



participant ":ToDoListController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant "greenSpaceRepository\n:GreenSpaceRepository" as GREENSpaceRepository
participant "listGreenSpace\n:List<GreenSpace>" as listGreenSpace
participant "toDoEntryMapper\n:toDoEntryMapper" as mapper
participant "greenSpace\n:GreenSpace" as GREEN
participant "listGreenSpaceDTO\n:List<GreenSpaceDTO>" as listDTO


activate CTRL

CTRL -> CTRL : getResponsible()
activate CTRL

CTRL -> _APP: getInstance()
activate _APP
_APP -> CTRL: appSession
deactivate _APP

CTRL -> APP: getCurrentSession()
activate APP
APP --> CTRL: currentSession
deactivate APP

CTRL -> SESSAO: getUserEmail()
activate SESSAO
SESSAO --> CTRL: responsibleEmail
deactivate SESSAO
deactivate CTRL

CTRL -> GREENSpaceRepository: getGreenSpacesByResponsible(responsibleEmail)
activate GREENSpaceRepository

GREENSpaceRepository -> listGreenSpace** : create
group loop [for each object in the GreenSpaceRepository]
    GREENSpaceRepository -> GREENSpaceRepository :  obj = get(i)
    activate GREENSpaceRepository
    deactivate GREENSpaceRepository

    GREENSpaceRepository -> GREEN** : getResponsible()
    activate GREEN
    GREEN -> GREEN : getResponsible()
    GREEN --> GREENSpaceRepository : objResponsible
    deactivate GREEN

    group if [objResponsible == responsibleEmail]
        GREENSpaceRepository -> listGreenSpace : add(obj)
        activate listGreenSpace
        deactivate listGreenSpace
    end
end
GREENSpaceRepository --> CTRL : listGreenSpaceByResponsible
deactivate GREENSpaceRepository

CTRL -> mapper : toDto(listGreenSpaceByResponsible)
activate mapper
mapper -> listDTO** : create
group loop [for each object in listGreenSpace]
    mapper -> listGreenSpace: obj = get(i)
    activate listGreenSpace
    deactivate listGreenSpace

    mapper -> mapper : objDto = toDTO(obj)
    activate mapper
    mapper --> objDto** : create(obj)
    deactivate mapper

    mapper -> listDTO : add(objDto)
    activate listDTO
    deactivate listDTO
end
mapper --> CTRL : listGreenSpaceDto


@enduml
