@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Register To-Do Entry

autonumber

participant ":ToDoListController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "toDoListRepository\n:toDoListRepository" as toDoListRepository
participant "toDoEntry\n:ToDoEntry" as TODO
participant "greenSpace\n:GreenSpace" as GREEN
participant "listGreenSpace\n:List<GreenSpace>" as listGreenSpace

activate CTRL

            CTRL -> CTRL : searchForGreenSpaceID(greenSpaceID)
            activate CTRL

                CTRL -> listGreenSpace: greenSpace  = get(greenSpaceID)
                activate listGreenSpace
                deactivate listGreenSpace


            deactivate CTRL



        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getToDoListRepository()
        activate PLAT

        PLAT --> CTRL: toDoListRepository
        deactivate PLAT

CTRL -> listGreenSpace: greenSpace = get(greenSpaceID)
activate listGreenSpace
deactivate listGreenSpace

CTRL -> toDoListRepository : registerToDoEntry(greenSpace, title, description, urgency, expectedDuration)
activate toDoListRepository

toDoListRepository -> TODO** : create
toDoListRepository -> toDoListRepository : addToDoEntry(toDoEntry)
toDoListRepository -> toDoListRepository : validateToDoEntry(toDoEntry)
toDoListRepository --> CTRL : toDoEntry
deactivate toDoListRepository


@enduml
