@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space Manager" as Employee
participant ":ToDoListUI" as UI
participant ":ToDoListController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository\n:GreenSpaceRepository" as GREENSpaceRepository
participant "toDoEntry" as ENTRY
participant "toDoListRepository\n:toDoListRepository" as toDoListRepository
participant "greenSpace\n:GreenSpace" as GREEN
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO

activate Employee

    Employee -> UI : ask to add a to-do entry
    activate UI

    UI -> CTRL** : create

    UI -> CTRL : getGreenSpacesByResponsible()
    activate CTRL

    CTRL -> CTRL : getResponsible()
    activate CTRL

                    CTRL -> _APP: getInstance()
                    activate _APP
                        _APP -> CTRL: appSession
                    deactivate _APP


                    CTRL -> APP: getCurrentSession()
                    activate APP

                        APP --> CTRL: currentSession
                    deactivate APP

                    CTRL -> SESSAO: getUserEmail()
                    activate SESSAO

                        SESSAO --> CTRL: email
                    deactivate SESSAO
                    CTRL --> CTRL
                    deactivate CTRL
                    |||

                    CTRL -> CTRL : getGreenSpacesByResponsible(email)
                    activate CTRL

                    CTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                    CTRL -> PLAT : getGreenSpaceRepository()
                    activate PLAT

                    PLAT --> CTRL: GreenSpaceRepository
                    deactivate PLAT

                    CTRL -> GREENSpaceRepository : getGreenSpacesByResponsible(email)

                    activate GREENSpaceRepository

                    GREENSpaceRepository -> CTRL : greenSpaces
                    deactivate GREENSpaceRepository
                    CTRL --> CTRL
                    deactivate CTRL


                    CTRL -> UI : greenSpaces

                    deactivate CTRL


        UI -> Employee : shows list of green spaces

        Employee -> UI : selects a green space from the list

        UI --> Employee : request data (title, description, urgency, expectedDuration)
    deactivate UI

    Employee -> UI : types requested data

    activate UI

        UI --> Employee : show all data registered\n and the confirmation menu
    deactivate UI

    Employee -> UI : submits data
    activate UI

    UI -> CTRL : registerToDoEntry(greenSpace ,title, description, urgency, expectedDuration)
    activate CTRL



        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getToDoListRepository()
        activate PLAT

        PLAT --> CTRL: toDoListRepository
        deactivate PLAT

    CTRL -> toDoListRepository : registerToDoEntry(greenSpace ,title, description, urgency, expectedDuration)
      deactivate CTRL
    activate toDoListRepository

    toDoListRepository -> GREEN** : create

    toDoListRepository -> toDoListRepository : addToDoEntry(toDoEntry)
    activate toDoListRepository

    toDoListRepository -> toDoListRepository : validateToDoEntry(toDoEntry)
    activate toDoListRepository

    toDoListRepository --> toDoListRepository
    deactivate toDoListRepository
    toDoListRepository --> toDoListRepository
    deactivate toDoListRepository

    toDoListRepository --> CTRL : toDoEntry
    deactivate toDoListRepository

    activate CTRL
    CTRL --> UI : toDoEntry
    deactivate CTRL

        UI --> Employee : shows operation (in)success
    deactivate UI

@enduml