@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":CreateCollaboratorUI" as UI
participant ":CreateCollaboratorController" as CTRL
participant "CollaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository

activate HRM

        HRM -> UI : asks to create a new collaborator

        activate UI

            UI -> CTRL** : create

                UI -> CTRL : getJobs()
                activate CTRL
        ref over CTRL
            Get Job list
        end ref
CTRL --> UI : jobsList
            deactivate CTRL

            UI --> HRM : shows jobsList list\n and asks to select one job
        deactivate UI

    HRM -> UI : selects a job
    activate UI

        UI --> HRM : requests data
    deactivate UI

    HRM -> UI : types requested data (name, birthDate, admissionDate,\naddress, phoneNumber, email, taxpayerNumber,\ndocType, docNumber)
    activate UI

        UI --> HRM : shows selected job and requested data
    deactivate UI

    HRM -> UI : submits data
    activate UI
    activate CTRL
    UI -> CTRL : submitData()

                ref over CTRL
                    Get Task Collaborator list
                end ref

                            CTRL -> CollaboratorRepository : registerCollaborator(name, birthDate, admissionDate,\naddress, phoneNumber, email, taxpayerNumber,\ndocType, docNumber and job)

                            activate CollaboratorRepository

                            ref over CollaboratorRepository
                                Register Collaborator
                            end ref

                            CollaboratorRepository --> CTRL : collaborator
                                    deactivate CollaboratorRepository

                        CTRL --> UI: collaborator
                        deactivate CTRL

                        UI --> HRM: Confirms the success of the operation.

                    deactivate UI

                deactivate HRM

                @enduml