@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox


participant ":AgendaController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "authenticationRepository\n:AuthenticationRepository" as authenticationRepository
participant "userSession\n:UserSession" as UserSession
participant "email\n:Email" as Email


 activate CTRL
autonumber 8
-> CTRL : getAgendaEntriesForResponsible()

autonumber 3.1
            CTRL -> CTRL : getResponsible()
    group Get Responsible
            activate CTRL

                CTRL -> PLAT  : getAuthenticationRepository()
                activate PLAT

                PLAT --> CTRL : authenticationRepository
                deactivate PLAT

                CTRL -> authenticationRepository : getCurrentUserSession()
                activate authenticationRepository

                    authenticationRepository --> CTRL : currentUserSession
                deactivate authenticationRepository

                CTRL -> UserSession : getUserId()
                activate UserSession

                    UserSession --> CTRL : userSession
                deactivate UserSession

                CTRL -> Email : getEmail()
                activate Email

                    Email --> CTRL : email
                deactivate Email

 deactivate CTRL
    end

@enduml
