@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods
package "GSM System" {

title Domain Model - US025



class GSM {
}

class AgendaEntry {
         toDoEntry
         StartingDate
         EndDate
         Team
         List<Vehicles>

}


class Agenda {
         List<AgendaEntry>
}





GSM "1" -- "*" AgendaEntry : cancel entry >
Agenda "1" - "*" AgendaEntry : posses >





@enduml