@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circles
hide methods

title Domain Model - US007

package "VFM System" {

    class VFM {
    }

    class ChekUp {
        licence
        date
        currentMileage
    }

    class Vehicle {
         plateID
         brand
         model
         type
         tare
         grossWeight
         millage
         registerDate
         acquisitionDate
         maintenanceFrequency
    }

    class Organization {
            name
            vatNumber
            website
            phoneNumber
            email
        }


    Vehicle "*" -- "1" Organization : has <

    VFM "1" -- "1" ChekUp : register >
    Vehicle "1" - "*" ChekUp : assigned <
}
@enduml