@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Collaborator" as Colab

participant ":CompletionTaskUI" as UI
participant ":Team Controller" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "teamRepository\n:TeamRepository" as teamRepository
participant "taskCompletionRepository:\nTaskCompletionRepository" as taskCompletionRepository
participant "taskCompletion\n:TaskCompletion" as CHECKUP

activate Colab

Colab -> UI : Asks to record the completion of a task
activate UI

UI -> Colab : Requests data (taxPayerNumber)
deactivate UI

Colab -> UI : Submits requested data
activate UI

UI -> CTRL : create

UI -> CTRL : getTeamByColabTaxNumber(taxPayerNumber)

deactivate UI

activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getTeamRepository()
activate PLAT

PLAT --> CTRL: teamRepository
deactivate PLAT

CTRL -> teamRepository : teamListContainsByTaxNumber(taxPayerNumber)

activate teamRepository

teamRepository -> CTRL : team
deactivate teamRepository


CTRL -> UI : team
deactivate CTRL

activate UI

UI -> Colab : Shows the list of tasks
Colab -> UI : Selects the desired task
UI -> Colab : Requests data (completionDate)
deactivate UI

Colab -> UI : Submits requested data
activate UI

UI -> CTRL : createCompletionOfTask(team, task, completionDate)
deactivate UI
activate CTRL

CTRL -> taskCompletionRepository : registerCompletion(team,task, completionDate)
activate taskCompletionRepository

taskCompletionRepository -> CHECKUP** : create
taskCompletionRepository -> taskCompletionRepository : addCompletion(completion)


 taskCompletionRepository -> taskCompletionRepository : validateCompletion(completion)

 taskCompletionRepository -> taskCompletionRepository : setTaskStatus(team)

taskCompletionRepository -> CTRL : completion
deactivate taskCompletionRepository


deactivate taskCompletionRepository

CTRL -> UI : completion


deactivate CTRL
activate UI


UI -> Colab : Displays operation success
deactivate UI

@enduml