@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant "taskCompletionRepository:\nTaskCompletionRepository" as taskCompletionRepository


autonumber 18

 -> taskCompletionRepository : registerCompletion(team,task, completionDate)
autonumber 18.1
activate taskCompletionRepository
    group Generate CheckUp List
taskCompletionRepository -> taskCompletionRepository : addCompletion(completion)


 taskCompletionRepository -> taskCompletionRepository : validateCompletion(completion)

 taskCompletionRepository -> taskCompletionRepository : setTaskStatus(team)


end

@enduml