@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":TeamController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT


autonumber 5

 -> CTRL : getTeamByColabTaxNumber(taxPayerNumber)
autonumber 5.1
activate CTRL
    group Get Team Repository


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getTeamRepository()
            activate PLAT

                PLAT --> CTRL: teamRepository
            deactivate PLAT









    end

deactivate CTRL


@enduml