@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":AssignSkillCollaboratoController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT

autonumber 3

 -> CTRL : assignSkillCollaboratorById(collaboratorId,skill)
autonumber 3.1
activate CTRL
    group Get Collaborator Repository


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getCollaboratorRepository()
            activate PLAT

                PLAT --> CTRL: CollaboratorRepository
            deactivate PLAT




    end
    autonumber 4
deactivate CTRL


@enduml