@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":AssignSkillCollaboratoController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository\n:SkillRepository" as TaskCategoryRepository

autonumber 3

 -> CTRL : getSkillList()
autonumber 3.1
activate CTRL
    group Get Skill List


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getSkillRepository()
            activate PLAT

                PLAT --> CTRL: skillRepository
            deactivate PLAT

            CTRL -> TaskCategoryRepository : getSkillList()
            activate TaskCategoryRepository

                TaskCategoryRepository --> CTRL : skillList
            deactivate TaskCategoryRepository


    end
    autonumber 4
    <-- CTRL  : skillList
deactivate CTRL


@enduml