@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":AssignSkillCollaboratorUI" as UI
participant ":AssignSkillCollaboratoController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository\n:CollaboratorRepository" as collaboratorRepository
participant "skillRepository\n:SkillRepository" as skillRepository
participant "skill\n:Skill" as EMPREGO

activate HRM

        HRM -> UI : asks to assign a skill to a collaborator


        activate UI

        UI -> CTRL** : create

        UI -> CTRL : getCollaboratorsList()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getSkillRepository()
            activate PLAT

            PLAT --> CTRL : skillRepository
            deactivate PLAT

            CTRL -> skillRepository : getSkillList()
            activate skillRepository

            skillRepository --> CTRL : skillList
            deactivate skillRepository

            CTRL -> UI :  skillList
            UI -> HRM : shows skillList

        deactivate CTRL



     UI --> HRM : request data (Collaborator ID Number)
    deactivate UI


    HRM -> UI : types requested data
    activate UI

    loop selects skills

        UI --> HRM : request data (skills)
        deactivate UI


        HRM -> UI : types requested data
        activate UI

    end

        UI --> HRM : show all data registered  for confirmation
        deactivate UI

        HRM -> UI : submits data
            activate UI


            UI -> CTRL : assignSkillCollaborator(collaboratorIdNumber, skills)
            activate CTRL


                CTRL -> skillRepository: assignSkillCollaborator(collaboratorIdNumber, skills)
                deactivate CTRL
                activate skillRepository



                skillRepository -> EMPREGO**: register(skillName)

                activate EMPREGO

                    EMPREGO -> EMPREGO : validateSkillName(skillName)
                    activate EMPREGO
                        EMPREGO --> EMPREGO
                deactivate EMPREGO
                                    skillRepository -> skillRepository: addSkill(skill)
                deactivate EMPREGO
                                    activate skillRepository
                                        skillRepository -> skillRepository: validateSkill(skill)
                                        activate skillRepository
                                            skillRepository --> skillRepository
                                        deactivate skillRepository

                                        skillRepository --> skillRepository
                                    deactivate skillRepository

                                    skillRepository --> CTRL : skill
                                    deactivate skillRepository
                                    activate CTRL

                CTRL --> UI: skill
                deactivate CTRL
                UI --> HRM: displays the success of the operation.

        deactivate UI
    deactivate HRM

@enduml