@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":AssignSkillCollaboratorUI" as UI
participant ":AssignSkillCollaboratorController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository\n:CollaboratorRepository" as collaboratorRepository
participant "skillRepository\n:SkillRepository" as skillRepository

activate HRM

        HRM -> UI : asks to assign a skill to a collaborator


        activate UI

        UI --> HRM : request data (collaboratorTaxNumber)
        deactivate UI


        HRM -> UI : confirms requested data
        activate UI

        UI -> CTRL** : create
         UI -> CTRL : containsCollaboratorByTaxNumber(collaboratorTaxNumber)
             activate CTRL
        CTRL -> RepositorySingleton : getInstance()




                                activate RepositorySingleton

                                RepositorySingleton --> CTRL : repositories
                                deactivate RepositorySingleton

                                CTRL -> PLAT : getCollaboratorRepository()
                                activate PLAT

                                PLAT --> CTRL : collaboratorRepository
                                deactivate PLAT

                                CTRL -> collaboratorRepository : isCollaboratorIDValid(collaboratorTaxNumber)
                                activate collaboratorRepository

                                collaboratorRepository -> CTRL : true/false
                                deactivate collaboratorRepository

                                CTRL -> UI : true/false
                                deactivate CTRL

                                UI -> HRM : displays that Tax Number is valid

                                UI -> CTRL : getSkillList()
            activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getSkillRepository()
            activate PLAT

            PLAT --> CTRL : skillRepository
            deactivate PLAT

            CTRL -> skillRepository : getSkillList()
            activate skillRepository

            skillRepository --> CTRL : skillList
            deactivate skillRepository


            CTRL -> UI :  skillList

        deactivate CTRL
            UI -> HRM : shows skillList
            deactivate UI






    loop selects skills

        UI --> HRM : request data (skill)
        deactivate UI


        HRM -> UI : selects  skill
        activate UI


        UI --> HRM : show all data registered  for confirmation
        deactivate UI

        HRM -> UI : submits data
            activate UI
    end







            UI -> CTRL :assignSkillCollaboratorByTaxNumber(collaboratorTaxNumber, skillName)
            activate CTRL


                        CTRL -> collaboratorRepository :assignSkillCollaborator(collaboratorTaxNumber, skill)
                        activate collaboratorRepository

                        collaboratorRepository -> collaboratorRepository : findCollaborator(collaboratorTaxNumber);


                        collaboratorRepository -> collaboratorRepository: addSkill(skill)










                        collaboratorRepository --> CTRL : true/false
                        deactivate collaboratorRepository







                CTRL --> UI: true/false

                deactivate CTRL
                UI --> HRM: displays the success of the operation.

        deactivate UI
    deactivate HRM

@enduml