@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Fleet\nManager" as FM
participant ":System" as System

activate FM

    FM -> System : Asks to register a vehicle's check-up.
    activate System

    System -> FM : Provides the FM the option to register a vehicle's check-up.
        deactivate System

        FM --> System : Provides all the required data.
    activate System

    System --> FM : Displays all the data that will be registered.
        deactivate System

        FM --> System : Confirms data.
        activate System

        System --> FM : If the data provided is inconsistent, notify the FM and suggest to insert again.
            deactivate System

            FM --> System : Provides all the required data again.
                activate System

        System --> FM : Displays all the data that will be registered.
                deactivate System

                FM --> System : Confirms data.
                activate System

        System --> FM : Validates and stores it.


        System --> FM : Confirms the success of the operation.
        deactivate System

@enduml