@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space Manager" as Employee
participant ":System" as System


activate Employee

    Employee -> System : ask to assign a vehicle to an agenda entry
    activate System

        System --> Employee : shows agenda entry list
    deactivate System

    Employee -> System : chooses an agenda entry from the list

    activate System

        System --> Employee : shows list of available vehicles
    deactivate System

     Employee -> System : chooses a vehicle from the list

     activate System

     System --> Employee : shows the confirmation menu
     deactivate System

    Employee -> System : submits data
    activate System

        System --> Employee : shows operation (in)success
    deactivate System

@enduml