@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods
package "VFM System" {

title Domain Model - US008

class GSM {
}

class ParkCollectedData {
age
recommendation
visitsFrequency
}

class MusgoSublime {
vatNumber
website
phoneNumber
email
}


MusgoSublime "1" - "1" ParkCollectedData: has >
ParkCollectedData "1" - "1" GSM: search <

@enduml