@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods
package "VFM System" {

title Domain Model - US008



class Collaborator {
}

class Agenda {
         Date
         Duration
         Vehicle
         Equipment
         ToDoList
         Status
         Team
}





Collaborator "1" -- "*" Agenda : lists tasks >





@enduml