@startuml
class Skill {
    - id: String
    - name: String
    - description: String

    + getId(): String
    + getName(): String
    + getDescription(): String
    + setName(name: String): void
    + setDescription(description: String): void
}
@enduml
