@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

title Domain Model - US001

hide circles
hide methods

package "HR System" {

    class HRM {
    }

    class Skills {
        name
    }

    class Organization {
        name
        vatNumber
        website
        phoneNumber
        email
    }

    HRM "1  " -- "1..*" Skills : creates >
    Organization "1" -- "                           *" Skills : has >
}



@enduml

