@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Domain Model - US001

hide circles
hide methods

package "HR System" {

    class HRM {
    }

    class Skill {
        name
    }

    class ListSkills {
        skills: List<Skill>
    }

    HRM "1" - "*" Skill : creates >
    HRM "1" - ListSkills : see >
    Skill "*" ---  ListSkills : registered >
}



@enduml

