@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Domain Model - US005

skinparam classAttributeIconSize 0

hide circles
hide methods

package "HRM Team Proposal System" {
    class HRM {
    }

    class Team {
        skills
        teamSize
    }

    class Organization {
        name
        vatNumber
        website
        phoneNumber
        email
    }

    HRM "1  " -- "1 " Team : generates >
    Organization "1 " --- "*" Team : has >
}
@enduml
