@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Domain Model - US005

skinparam classAttributeIconSize 0

hide circles
hide methods

package "HRM Team Proposal System" {
    class HRM {
    }

    class TeamProposal {
        - skills: string[]
        - teamSize: int
    }

    class Collaborators {
        - name: String
        - skills: String[]
        - workerID: int
        - age: int
    }

    HRM "1" -- "1 " TeamProposal : generates >
    TeamProposal "0..* " -- "0..* " Collaborators : has >
}
@enduml
