ººº@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : request to register a vehicle
    activate System

        System --> Employee : request data(plateID, brand, model)
            deactivate System

    Employee -> System : types data

    activate System

    System --> Employee : shows types of vehicles\n and request a selection
    deactivate System

    Employee -> System : Select a type
    activate System

    System --> Employee : request data(tareweight,grossweight...)
    deactivate System

    Employee -> System : types data

    activate System

    System --> Employee : show all data registered\n and the confirmation menu
    deactivate System

    Employee -> System : submits data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml