@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods
package "GSM System" {

title Domain Model - US027



class GSM {
}

class GreenSpace {
         name
         size
         area
         address
         responsible
}

class sortedGreenSpaces {
    sortMethod
}


GSM "1" -- "1" sortedGreenSpaces : lists managed green spaces >
sortedGreenSpaces "1" -- "*" GreenSpace : get >





@enduml