@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "User" as User
participant ":System" as System

        activate User

        User --> System: Asks to respond the user park questionnaire
        activate System

        System -> User : Request data (Age, Recommendation, Visits Frequency)
        deactivate System
        User -> System : Types requested data (Age, Recommendation, Visits Frequency)

        activate System

        System --> User : Shows entered data and request confirmation
        deactivate System

        User -> System : Confirms submitted data
        activate System

        System --> User : Shows operation success
        deactivate System
        deactivate User
@enduml