@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "vehicleRepository:\nVehicleRepository" as ORG
participant "vehicle\n:Vehicle" as TAREFA

autonumber 16
-> ORG: registerVehicle(plate ID,brand, model, type, Tare Weight,\n Gross Weight, millage, Register date, acquisition date,\nmaintenance frequency, last checkup)

autonumber 16.1
activate ORG
    group Register Vehicle

        ORG -> TAREFA**: registerVehicle(plate ID,brand, model, type, Tare Weight,\n Gross Weight, millage, Register date, acquisition date,\nmaintenance frequency, last checkup)
        ORG -> ORG: addVehicle (Vehicle)

        activate ORG
            ORG -> ORG: validateVehicle(Vehicle)
            activate ORG
                ORG --> ORG
            deactivate ORG

            ORG --> ORG
        deactivate ORG
    end

    autonumber 17
    <-- ORG : vehicle
deactivate ORG


@enduml