@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle Fleet Manager" as VFM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as vehicleRepository

activate VFM

        VFM -> UI : asks to register a new vehicle

        activate UI


            UI -> CTRL** : create


            UI --> VFM : request data
            deactivate UI

            VFM -> UI : registerVehicle(plateID, brand, model...)
            activate UI



        UI --> VFM : show all data registered  for confirmation
        deactivate UI

    VFM -> UI : data
    activate UI

        UI -> CTRL : registerVehicle(plateID, brand, model...)
            ref over CTRL
                Get Vehicle Repository
            end
        activate CTRL




            CTRL -> vehicleRepository: registerVehicle(plateID, brand, model...)
            activate vehicleRepository

            ref over vehicleRepository
                Register Vehicle
            end





                vehicleRepository --> CTRL : vehicle

            deactivate vehicleRepository

            CTRL --> UI: vehicle
            deactivate CTRL
            UI --> VFM: displays operation success
    deactivate UI

deactivate VFM

@enduml