@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as TaskCategoryRepository

autonumber 3

 -> CTRL : getVehicle()
autonumber 3.1
activate CTRL
    group Get Vehicle List


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getVehicleRepository()
            activate PLAT

                PLAT --> CTRL: vehicleRepository
            deactivate PLAT

            CTRL -> TaskCategoryRepository : getVehicleList()
            activate TaskCategoryRepository

                TaskCategoryRepository --> CTRL : vehicleList
            deactivate TaskCategoryRepository


    end
    autonumber 4
    <-- CTRL  : vehicleList
deactivate CTRL


@enduml