@startuml
class Vehicle {
    - plateID : int
    - brand: String
    - model: String
    - type: String
    - tareWeight: String
    - grossWeight: String
    - currentKm: String
    - registerDate: String
    - acquisitionDate: String
    - maintenanceFrequency: String

}
@enduml
