@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circles
hide methods

title Domain Model - US006

package "FM System" {

    class FM {
    }

    class Vehicle {
         plateID
         brand
         model
         type
         tare
         grossWeight
         kms
         registerDate
         acquisitionDate
         maintenanceFrequency
    }

    class Organization {
            name
            vatNumber
            website
            phoneNumber
            email
        }


    FM "1" - "*" Vehicle : creates >
    Vehicle "*" -- "1" Organization : has <
}
@enduml