@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Collaborator" as COLAB
participant ":System" as System


        COLAB -> System: Asks to record the completion of a task
        activate COLAB
        activate System

        System --> COLAB : Requests data (taxPayerNumber)
        COLAB -> System: Submits requested data
        System --> COLAB : Shows the list of tasks
        COLAB -> System: Selects the desired task
        System --> COLAB: Requests data (completionDate)
        COLAB -> System: Submits requested data
        System --> COLAB: Displays operation success


        deactivate System
        deactivate COLAB
@enduml