@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US003

'class Platform {
'  -description
'}

package "HRM" {

    class Organization {
        name
        vatNumber
        website
        phoneNumber
        email
    }

    class Collaborator {
        name
        birthdate
        admissionDate
        address
        phoneNumber
        email
        taxpayerNumber
        id_doc_type
        id_doc_number
    }

    class HRM {
        name
    }

    HRM "1" - "1..*" Collaborator : creates >
    Organization "1" -- "1..*" Collaborator : has >


}




@enduml