@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US003

'class Platform {
'  -description
'}

package "HRM" {

    class HRM {

    }

    class Collaborator {
    }

    HRM "1" - "1..*" Collaborator : create >
}




@enduml