@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US010

class User {

}



User "1" - "*" Vehicle: has >
Vehicle "*"- "*" VehicleForCheckUp: contains >
VehicleForCheckUp "*" -- "1" VFM : informs >

@enduml