@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources Manager" as Employee
participant "System" as System

activate Employee

    System <- Employee : asks to generate a team proposal
    activate System

        Employee <-- System : requests data (skills; experience; availability; vehicles, machines and equipment required)
    deactivate System

    Employee -> System : selects a task category
    activate System

        Employee -> System : selects a task category
    deactivate System

    Employee -> System : shows multiple or a single team generation
    activate System

        System --> Employee : shows task category list and asks to select one
    deactivate System

    Employee -> System : selects a task category
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml